### ISSUE TITLE
Status Update (April 2016)

### ISSUE THREAD

**Issue by apavlo** [cmu-db/dbdb.io#13]
1. Remove the "Current Version" field from the `System` admin form. Also remove the "slug" and "secret" fields from the form; these should be auto-generated when the `System` object is saved.

2. What does the "creator" field mean in `Systems`?

3. Remove the "Version" field from the `System Version` form. 

4. Why is a `Feature Option` tied to a `System Version`? It should be tied to a `Feature`.

**Comment by aquafemi** [comment]
1. Done. The only issue I have with this is that if a fixture is used to load System data, it won't generate a secret key. I do see that in views, when a database is created the key is auto-generated though but doesn't the secret key still need to exist as a field or do you mean something else when you say field?
2. Now that you mention it, I only see creator used for `SystemVersion` revisions, so I'll take it out from `System`.
3. Do you mean the `version_number`? I thought that it was needed for doing queries such as finding which `SystemVersion`'s `version_number` matches a `System`'s `current_version` or for the revisions page
4. I've applied your fix so that it isn't tied to `System Version` anymore.I  

Also just to give you a heads up I took out the multivalued attribute because I think I could just display/select all feature options in the same way to simplify things.
